### ISSUE TITLE
For application/pdf iterate over pages adding canvas to sequence per page

### ISSUE THREAD

**Issue by wwelling** [TAMULib/IRIIIFService#100]
Two-stage implementations with a temp release. 

For pdf resources.

1. Implement hack against current cantaloupe that passes `?page=99999` and parses error to get page number
2. Cantaloupe v5.0 custom delegate to add page count to image manifest info.json

Both will require creating and adding canvas to sequence per page.

**Comment by jcreel** [comment]
Will resolve https://github.com/TAMULib/SAGE/issues/302

**Comment by jcreel** [comment]
Hold off on merging until completion of #104
