### ISSUE TITLE
Mirador 3 compatibility

### ISSUE THREAD

**Issue by wwelling** [TAMULib/IRIIIFService#104]
Loading the manifest you have another option in the upper right hamburger/ellipse 
https://demos.library.tamu.edu/mirador/?manifest=https://api-pre.library.tamu.edu/fcrepo/rest/mwbManifests/tcc0005/tcc0005_none

With our manifests, it doesn’t trigger an automatic download.  It spawns a new window.  Not quite sure what is missing for that yet.

Using a testing manifest it does work as expected.

https://demos.library.tamu.edu/mirador/?manifest=https://purl.stanford.edu/bb020ty1503/iiif/manifest

**Comment by jcreel** [comment]
We need to use meta-identifiers in the page requests instead of query parameters.
