### ISSUE TITLE
Request for documentation on recomended PCDM structure for best compatibility

### ISSUE THREAD

**Issue by Surfrdan** [TAMULib/IRIIIFService#116]
Is it possible for the documentation to provide best practice on how your PCDM models should be structured for best compatibility with the IRIIIF service ? 

Alternatively, could a sample of  known-good PCDM be shared with the community ? 

I suspect PCDM drives the user in a fairly rigid direction but I am aware of certain interpretations which might not match up with the softwares expected input.

**Comment by wwelling** [comment]
@Surfrdan thank you for submitting this issue. Sorry for the delay in addressing. Documentation and example are both reasonable requests and we will work on supplying theme in either README or Wiki.
