### ISSUE TITLE
Unable to retrieve cached manifests

### ISSUE THREAD

**Issue by jcreel** [TAMULib/IRIIIFService#126]
For example, https://api-dev.library.tamu.edu/iiif-service/fedora/collection/london-maps-2 returns a 500 error.

java.lang.IllegalStateException: Cannot set property creation because no setter, no wither and it's not part of the persistence constructor public edu.tamu.iiif.model.RedisManifest()
12/19/2022 11:04:08 AM 	at org.springframework.data.mapping.model.InstantiationAwarePropertyAccessor.setProperty(InstantiationAwarePropertyAccessor.java:119) ~[spring-data-commons-2.6.6.jar!/:2.6.6]
12/19/2022 11:04:08 AM 	at org.springframework.data.redis.core.convert.MappingRedisConverter.lambda$doReadInternal$0(MappingRedisConverter.java:253) ~[spring-data-redis-2.6.6.jar!/:2.6.6]
12/19/2022 11:04:08 AM 	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:361) ~[spring-data-commons-2.6.6.jar!/:2.6.6]

**Comment by wwelling** [comment]
Redis cache was corrupt.

![image](https://user-images.githubusercontent.com/8352733/208485624-c23f2896-29c6-41c0-8c4b-c70752020894.png)
