### ISSUE TITLE
config location for redis/remote resolver does not match the bundled application.yml location

### ISSUE THREAD

**Issue by LlGC-dof** [TAMULib/IRIIIFService#143]
**Describe the bug**

https://github.com/TAMULib/IRIIIFService/blob/1e8ae9554389737fecf9534124d0cd82e5687faa/src/main/resources/application.yml#L38

The bundled application.yml defines the resolver type at  ```iiif.resolver.type``` However the RemoteResourceResolver and RedisResourceResolver classes are looking in ```iiif.resolver``` 

PR to follow which corrects the location in the code so as not to change users deployed configurations.

**Comment by LlGC-dof** [comment]
PR https://github.com/LlGC-dof/IRIIIFService/pull/new/issue-143

**Comment by wwelling** [comment]
Thanks.
